import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Tourney } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: '--font-poppins',
})

const tourney = Tourney({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: '--font-tourney',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${tourney.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
